services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  product_database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"  
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - product_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  commande_database:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_DATABASE: commanddb
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - commande_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  gateway:
    build:
      context: ./modules/MarketGatewayAPI
    ports:
      - "3000:80"

  product:
    build:
      context: ./modules/ProductServiceAPI
    ports:
      - "5002:81"
    environment:
      - ConnectionStrings__Product_ConnectionString=server=product_database;port=3306;database=productdb;user=root;password=root
    depends_on:
      rabbitmq:
        condition: service_healthy
      product_database:
        condition: service_healthy

  command:
    build:
      context: ./modules/CommandServiceAPI
    ports:
      - "5037:82"
    environment:
      - ConnectionStrings__Command_ConnectionString=server=commande_database;port=3306;database=commanddb;user=root;password=root
    depends_on:
      rabbitmq:
        condition: service_healthy
      commande_database:
        condition: service_healthy

volumes:
  product_mysql_data:
  commande_mysql_data: